version: "3.0"
services:
  api:
    container_name: api
    image: api-lumen-58
    build:
      dockerfile: ./php/Dockerfile
      context: .
    volumes:
      - ../api/:/app
    networks:
      - development-network
  webserver:
    container_name: webserver
    image: "nginx:1.13.8-alpine"
    volumes:
      - ../api/:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - development-network
networks:
  development-network:
    driver: bridge